version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: brevly-db-dev
    environment:
      POSTGRES_DB: brevly
      POSTGRES_USER: brevly_user
      POSTGRES_PASSWORD: brevly_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_dev_data: 